"""add claim evaluations cache

Revision ID: 15de042fe35f
Revises: 259284533d13
Create Date: 2026-02-04 12:11:39.993507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15de042fe35f'
down_revision: Union[str, Sequence[str], None] = '259284533d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('best_action_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('relevance', sa.String(), nullable=True),
    sa.Column('progress', sa.String(), nullable=True),
    sa.Column('timing', sa.String(), nullable=True),
    sa.Column('why_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['best_action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_evaluations_best_action_id'), 'claim_evaluations', ['best_action_id'], unique=False)
    op.create_index(op.f('ix_claim_evaluations_claim_id'), 'claim_evaluations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evaluations_id'), 'claim_evaluations', ['id'], unique=False)
    op.create_index(op.f('ix_claim_evaluations_person_id'), 'claim_evaluations', ['person_id'], unique=False)
    op.create_index(op.f('ix_claim_evaluations_progress'), 'claim_evaluations', ['progress'], unique=False)
    op.create_index(op.f('ix_claim_evaluations_relevance'), 'claim_evaluations', ['relevance'], unique=False)
    op.create_index(op.f('ix_claim_evaluations_tier'), 'claim_evaluations', ['tier'], unique=False)
    op.create_index(op.f('ix_claim_evaluations_timing'), 'claim_evaluations', ['timing'], unique=False)
    # op.alter_column('claims', 'person_id',\r\n    #            existing_type=sa.VARCHAR(),\r\n    #            nullable=False)
    # op.alter_column('claims', 'text',\r\n    #            existing_type=sa.TEXT(),\r\n    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('claims', 'text',\r\n    #            existing_type=sa.TEXT(),\r\n    #            nullable=True)
    # op.alter_column('claims', 'person_id',\r\n    #            existing_type=sa.VARCHAR(),\r\n    #            nullable=True)
    op.drop_index(op.f('ix_claim_evaluations_timing'), table_name='claim_evaluations')
    op.drop_index(op.f('ix_claim_evaluations_tier'), table_name='claim_evaluations')
    op.drop_index(op.f('ix_claim_evaluations_relevance'), table_name='claim_evaluations')
    op.drop_index(op.f('ix_claim_evaluations_progress'), table_name='claim_evaluations')
    op.drop_index(op.f('ix_claim_evaluations_person_id'), table_name='claim_evaluations')
    op.drop_index(op.f('ix_claim_evaluations_id'), table_name='claim_evaluations')
    op.drop_index(op.f('ix_claim_evaluations_claim_id'), table_name='claim_evaluations')
    op.drop_index(op.f('ix_claim_evaluations_best_action_id'), table_name='claim_evaluations')
    op.drop_table('claim_evaluations')
    # ### end Alembic commands ###

