"""add action enrichment columns

Revision ID: 259284533d13
Revises: 6933516af06d
Create Date: 2026-02-04 12:04:50.051473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '259284533d13'
down_revision: Union[str, Sequence[str], None] = '6933516af06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('policy_area', sa.String(), nullable=True))
    op.add_column('actions', sa.Column('latest_action_text', sa.Text(), nullable=True))
    op.add_column('actions', sa.Column('latest_action_date', sa.String(), nullable=True))
    # op.alter_column('claims', 'person_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('claims', 'text',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    op.create_index(op.f('ix_claims_intent'), 'claims', ['intent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_intent'), table_name='claims')
    # op.alter_column('claims', 'text',
    #            existing_type=sa.TEXT(),
    #            nullable=True)
    # op.alter_column('claims', 'person_id',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    op.drop_column('actions', 'latest_action_date')
    op.drop_column('actions', 'latest_action_text')
    op.drop_column('actions', 'policy_area')
    # ### end Alembic commands ###
