"""add intent to claims

Revision ID: 6933516af06d
Revises: 02a829ae6361
Create Date: 2026-02-04 10:59:36.642833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6933516af06d'
down_revision: Union[str, Sequence[str], None] = '02a829ae6361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('intent', sa.String(), nullable=True))
    op.alter_column('claims', 'person_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claims', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_claims_intent'), 'claims', ['intent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_intent'), table_name='claims')
    op.alter_column('claims', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('claims', 'person_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('claims', 'intent')
    # ### end Alembic commands ###
