"""sync claim category

Revision ID: f51a064fe715
Revises: 
Create Date: 2026-02-04 10:21:13.127400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f51a064fe715'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('category', sa.String(), server_default='general', nullable=False))
    op.alter_column('claims', 'person_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('claims', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_claims_category'), 'claims', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_category'), table_name='claims')
    op.alter_column('claims', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('claims', 'person_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('claims', 'category')
    # ### end Alembic commands ###
