"""
Agriculture sector routes.

Common endpoints generated by the sector factory.
"""

from models.agriculture_models import (
    TrackedAgricultureCompany,
    SECAgricultureFiling,
    AgricultureGovernmentContract,
    AgricultureLobbyingRecord,
    AgricultureEnforcement,
)
from routers.sector_factory import create_sector_router
from services.sector_queries import SectorConfig

config = SectorConfig(
    prefix="/agriculture",
    tag="agriculture",
    entity_label="companies",
    entity_id_field="company_id",
    entity_type_donations="agriculture",
    entity_type_stock="agriculture_company",
    entity_model=TrackedAgricultureCompany,
    lobbying_model=AgricultureLobbyingRecord,
    contract_model=AgricultureGovernmentContract,
    enforcement_model=AgricultureEnforcement,
    filing_model=SECAgricultureFiling,
    list_count_models=[
        (AgricultureGovernmentContract, "contract_count"),
        (SECAgricultureFiling, "filing_count"),
        (AgricultureEnforcement, "enforcement_count"),
    ],
)

router = create_sector_router(config)
