"""
Chemicals sector routes — Companies, contracts, lobbying, enforcement, SEC filings, stock.

Common endpoints (dashboard, list, detail, lobbying, contracts, enforcement,
donations, filings, stock, compare, trends) are generated by the sector factory.
"""

from models.chemicals_models import (
    TrackedChemicalCompany,
    SECChemicalFiling,
    ChemicalGovernmentContract,
    ChemicalLobbyingRecord,
    ChemicalEnforcement,
)
from routers.sector_factory import create_sector_router
from services.sector_queries import SectorConfig

config = SectorConfig(
    prefix="/chemicals",
    tag="chemicals",
    entity_label="companies",
    entity_id_field="company_id",
    entity_type_donations="chemicals",
    entity_type_stock="chemicals_company",
    entity_model=TrackedChemicalCompany,
    lobbying_model=ChemicalLobbyingRecord,
    contract_model=ChemicalGovernmentContract,
    enforcement_model=ChemicalEnforcement,
    filing_model=SECChemicalFiling,
    list_count_models=[
        (ChemicalGovernmentContract, "contract_count"),
        (SECChemicalFiling, "filing_count"),
        (ChemicalEnforcement, "enforcement_count"),
        (ChemicalLobbyingRecord, "lobbying_count"),
    ],
)

router = create_sector_router(config)
