"""
Defense sector routes.

Common endpoints generated by the sector factory.
Sector-specific: SAM.gov exclusions and entity registration.
"""

from fastapi import Depends, Query
from sqlalchemy import desc
from sqlalchemy.orm import Session

from models.database import get_db
from models.defense_models import (
    TrackedDefenseCompany,
    SECDefenseFiling,
    DefenseGovernmentContract,
    DefenseLobbyingRecord,
    DefenseEnforcement,
)
from models.government_data_models import SAMExclusion, SAMEntity
from routers.sector_factory import create_sector_router
from services.sector_queries import SectorConfig

config = SectorConfig(
    prefix="/defense",
    tag="defense",
    entity_label="companies",
    entity_id_field="company_id",
    entity_type_donations="defense",
    entity_type_stock="defense_company",
    entity_model=TrackedDefenseCompany,
    lobbying_model=DefenseLobbyingRecord,
    contract_model=DefenseGovernmentContract,
    enforcement_model=DefenseEnforcement,
    filing_model=SECDefenseFiling,
    list_count_models=[
        (DefenseGovernmentContract, "contract_count"),
        (SECDefenseFiling, "filing_count"),
        (DefenseEnforcement, "enforcement_count"),
        (DefenseLobbyingRecord, "lobbying_count"),
    ],
)

router = create_sector_router(config)


# ── Defense-specific: SAM.gov Data ───────────────────────────────────────────


@router.get("/companies/{entity_id}/exclusions")
def get_defense_company_exclusions(
    entity_id: str,
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    """Get SAM.gov exclusion (debarment/suspension) records for a defense company."""
    q = db.query(SAMExclusion).filter(SAMExclusion.company_id == entity_id)
    total = q.count()
    exclusions = (
        q.order_by(desc(SAMExclusion.activation_date))
        .offset(offset)
        .limit(limit)
        .all()
    )
    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "exclusions": [
            {
                "id": e.id,
                "sam_number": e.sam_number,
                "entity_name": e.entity_name,
                "exclusion_type": e.exclusion_type,
                "excluding_agency": e.excluding_agency,
                "classification": e.classification,
                "activation_date": str(e.activation_date) if e.activation_date else None,
                "termination_date": str(e.termination_date) if e.termination_date else None,
                "description": e.description,
            }
            for e in exclusions
        ],
    }


@router.get("/companies/{entity_id}/sam-entity")
def get_defense_company_sam_entity(
    entity_id: str,
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    """Get SAM.gov entity registration data (UEI, CAGE, NAICS, parent/subsidiary)."""
    q = db.query(SAMEntity).filter(SAMEntity.company_id == entity_id)
    total = q.count()
    entities = q.offset(offset).limit(limit).all()
    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "entities": [
            {
                "id": e.id,
                "uei": e.uei,
                "cage_code": e.cage_code,
                "legal_business_name": e.legal_business_name,
                "dba_name": e.dba_name,
                "physical_address": e.physical_address,
                "naics_codes": e.naics_codes,
                "parent_uei": e.parent_uei,
                "parent_name": e.parent_name,
                "registration_status": e.registration_status,
                "exclusion_status_flag": e.exclusion_status_flag,
            }
            for e in entities
        ],
    }
