"""
Education sector routes.

Common endpoints generated by the sector factory.
"""

from models.education_models import (
    TrackedEducationCompany,
    SECEducationFiling,
    EducationGovernmentContract,
    EducationLobbyingRecord,
    EducationEnforcement,
)
from routers.sector_factory import create_sector_router
from services.sector_queries import SectorConfig

config = SectorConfig(
    prefix="/education",
    tag="education",
    entity_label="companies",
    entity_id_field="company_id",
    entity_type_donations="education",
    entity_type_stock="education_company",
    entity_model=TrackedEducationCompany,
    lobbying_model=EducationLobbyingRecord,
    contract_model=EducationGovernmentContract,
    enforcement_model=EducationEnforcement,
    filing_model=SECEducationFiling,
    list_count_models=[
        (EducationGovernmentContract, "contract_count"),
        (SECEducationFiling, "filing_count"),
        (EducationEnforcement, "enforcement_count"),
        (EducationLobbyingRecord, "lobbying_count"),
    ],
)

router = create_sector_router(config)
