"""
Energy sector routes.

Common endpoints generated by the sector factory.
Sector-specific: EPA greenhouse gas emissions data.
"""

from typing import Optional

from fastapi import Depends, HTTPException, Query
from sqlalchemy import desc, func, or_
from sqlalchemy.orm import Session

from models.database import get_db
from models.energy_models import (
    TrackedEnergyCompany,
    SECEnergyFiling,
    EnergyEmission,
    EnergyGovernmentContract,
    EnergyLobbyingRecord,
    EnergyEnforcement,
)
from routers.sector_factory import create_sector_router
from services.sector_queries import SectorConfig

config = SectorConfig(
    prefix="/energy",
    tag="energy",
    entity_label="companies",
    entity_id_field="company_id",
    entity_type_donations="energy",
    entity_type_stock="energy_company",
    entity_model=TrackedEnergyCompany,
    lobbying_model=EnergyLobbyingRecord,
    contract_model=EnergyGovernmentContract,
    enforcement_model=EnergyEnforcement,
    filing_model=SECEnergyFiling,
    list_count_models=[
        (EnergyGovernmentContract, "contract_count"),
        (SECEnergyFiling, "filing_count"),
        (EnergyEnforcement, "enforcement_count"),
    ],
)

router = create_sector_router(config)


# ── Energy-specific: EPA Emissions ───────────────────────────────────────────


@router.get("/companies/{entity_id}/emissions")
def get_energy_company_emissions(
    entity_id: str,
    reporting_year: Optional[int] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    """EPA greenhouse gas emission reports for an energy company."""
    co = db.query(TrackedEnergyCompany).filter_by(company_id=entity_id).first()
    if not co:
        raise HTTPException(status_code=404, detail="Energy company not found")

    query = db.query(EnergyEmission).filter_by(company_id=entity_id)
    if reporting_year:
        query = query.filter(EnergyEmission.reporting_year == reporting_year)
    total = query.count()
    records = query.order_by(desc(EnergyEmission.reporting_year)).offset(offset).limit(limit).all()
    total_co2e = (
        db.query(func.sum(EnergyEmission.total_emissions))
        .filter_by(company_id=entity_id)
        .scalar() or 0
    )

    return {
        "total": total,
        "total_co2e": total_co2e,
        "limit": limit,
        "offset": offset,
        "emissions": [
            {
                "id": e.id,
                "facility_name": e.facility_name,
                "facility_id_epa": getattr(e, "facility_id_epa", None),
                "facility_city": getattr(e, "facility_city", None),
                "facility_state": e.facility_state,
                "reporting_year": e.reporting_year,
                "total_emissions": e.total_emissions,
                "emission_type": e.emission_type,
                "industry_type": e.industry_type,
                "source_url": e.source_url,
            }
            for e in records
        ],
    }


@router.get("/companies/{entity_id}/emissions/summary")
def get_energy_company_emissions_summary(entity_id: str, db: Session = Depends(get_db)):
    """Emissions summary with YoY change and climate lobbying cross-reference."""
    co = db.query(TrackedEnergyCompany).filter_by(company_id=entity_id).first()
    if not co:
        raise HTTPException(status_code=404, detail="Energy company not found")

    total_records = db.query(EnergyEmission).filter_by(company_id=entity_id).count()
    total_co2e = (
        db.query(func.sum(EnergyEmission.total_emissions))
        .filter_by(company_id=entity_id)
        .scalar() or 0
    )

    by_year = {}
    rows = (
        db.query(EnergyEmission.reporting_year, func.sum(EnergyEmission.total_emissions), func.count())
        .filter_by(company_id=entity_id)
        .group_by(EnergyEmission.reporting_year)
        .order_by(EnergyEmission.reporting_year)
        .all()
    )
    for year, emissions, count in rows:
        by_year[str(year)] = {"total_emissions": emissions or 0, "facilities": count}

    by_state = {}
    rows = (
        db.query(EnergyEmission.facility_state, func.sum(EnergyEmission.total_emissions), func.count())
        .filter_by(company_id=entity_id)
        .group_by(EnergyEmission.facility_state)
        .order_by(func.sum(EnergyEmission.total_emissions).desc())
        .limit(10)
        .all()
    )
    for state, emissions, count in rows:
        if state:
            by_state[state] = {"total_emissions": emissions or 0, "facilities": count}

    year_keys = sorted(by_year.keys())
    yoy_change = None
    if len(year_keys) >= 2:
        curr = by_year[year_keys[-1]]["total_emissions"]
        prev = by_year[year_keys[-2]]["total_emissions"]
        if prev and prev > 0:
            yoy_change = round(((curr - prev) / prev) * 100, 1)

    # Climate lobbying cross-reference
    climate_keywords = [
        "climate", "emission", "greenhouse", "carbon", "clean energy",
        "renewable", "epa", "environmental", "pollution", "methane",
    ]
    climate_lobby_filters = []
    for kw in climate_keywords:
        pattern = f"%{kw}%"
        climate_lobby_filters.append(EnergyLobbyingRecord.lobbying_issues.ilike(pattern))
        climate_lobby_filters.append(EnergyLobbyingRecord.specific_issues.ilike(pattern))

    climate_lobbying_count = (
        db.query(func.count(EnergyLobbyingRecord.id))
        .filter(EnergyLobbyingRecord.company_id == entity_id, or_(*climate_lobby_filters))
        .scalar() or 0
    )
    climate_lobbying_spend = (
        db.query(func.sum(EnergyLobbyingRecord.income))
        .filter(EnergyLobbyingRecord.company_id == entity_id, or_(*climate_lobby_filters))
        .scalar() or 0
    )

    return {
        "total_records": total_records,
        "total_co2e": total_co2e,
        "by_year": by_year,
        "by_state": by_state,
        "yoy_change_pct": yoy_change,
        "climate_lobbying_count": climate_lobbying_count,
        "climate_lobbying_spend": float(climate_lobbying_spend),
    }
