"""
Telecommunications sector routes.

Common endpoints generated by the sector factory.
"""

from models.telecom_models import (
    TrackedTelecomCompany,
    SECTelecomFiling,
    TelecomGovernmentContract,
    TelecomLobbyingRecord,
    TelecomEnforcement,
)
from routers.sector_factory import create_sector_router
from services.sector_queries import SectorConfig

config = SectorConfig(
    prefix="/telecom",
    tag="telecom",
    entity_label="companies",
    entity_id_field="company_id",
    entity_type_donations="telecom",
    entity_type_stock="telecom_company",
    entity_model=TrackedTelecomCompany,
    lobbying_model=TelecomLobbyingRecord,
    contract_model=TelecomGovernmentContract,
    enforcement_model=TelecomEnforcement,
    filing_model=SECTelecomFiling,
    list_count_models=[
        (TelecomGovernmentContract, "contract_count"),
        (SECTelecomFiling, "filing_count"),
        (TelecomEnforcement, "enforcement_count"),
    ],
)

router = create_sector_router(config)
