"""
Transportation sector routes.

Common endpoints generated by the sector factory.
Sector-specific: NHTSA recalls, complaints, safety ratings, fuel economy.
"""

import datetime
from typing import Optional

from fastapi import Depends, HTTPException, Query
from sqlalchemy import desc, func
from sqlalchemy.orm import Session

from models.database import get_db
from models.transportation_models import (
    TrackedTransportationCompany,
    SECTransportationFiling,
    TransportationGovernmentContract,
    TransportationLobbyingRecord,
    TransportationEnforcement,
    NHTSARecall,
    NHTSAComplaint,
    NHTSASafetyRating,
    FuelEconomyVehicle,
)
from routers.sector_factory import create_sector_router
from services.sector_queries import SectorConfig
from utils.db_compat import extract_year

config = SectorConfig(
    prefix="/transportation",
    tag="transportation",
    entity_label="companies",
    entity_id_field="company_id",
    entity_type_donations="transportation",
    entity_type_stock="transportation_company",
    entity_model=TrackedTransportationCompany,
    lobbying_model=TransportationLobbyingRecord,
    contract_model=TransportationGovernmentContract,
    enforcement_model=TransportationEnforcement,
    filing_model=SECTransportationFiling,
    list_count_models=[
        (TransportationGovernmentContract, "contract_count"),
        (SECTransportationFiling, "filing_count"),
        (TransportationEnforcement, "enforcement_count"),
    ],
)

router = create_sector_router(config)


# ── Transportation-specific: NHTSA Data ──────────────────────────────────────


@router.get("/companies/{entity_id}/recalls")
def get_transportation_company_recalls(
    entity_id: str,
    model_year: Optional[int] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    """NHTSA recall campaigns for a transportation company."""
    co = db.query(TrackedTransportationCompany).filter_by(company_id=entity_id).first()
    if not co:
        raise HTTPException(status_code=404, detail="Transportation company not found")

    query = db.query(NHTSARecall).filter_by(company_id=entity_id)
    if model_year:
        query = query.filter(NHTSARecall.model_year == model_year)
    total = query.count()
    recalls = query.order_by(desc(NHTSARecall.recall_date)).offset(offset).limit(limit).all()

    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "recalls": [
            {
                "id": r.id,
                "recall_number": r.recall_number,
                "make": r.make,
                "model": r.model,
                "model_year": r.model_year,
                "recall_date": r.recall_date,
                "component": r.component,
                "summary": r.summary,
                "consequence": r.consequence,
                "remedy": r.remedy,
                "manufacturer": r.manufacturer,
            }
            for r in recalls
        ],
    }


@router.get("/companies/{entity_id}/complaints")
def get_transportation_company_complaints(
    entity_id: str,
    model_year: Optional[int] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    """NHTSA complaint records for a transportation company."""
    co = db.query(TrackedTransportationCompany).filter_by(company_id=entity_id).first()
    if not co:
        raise HTTPException(status_code=404, detail="Transportation company not found")

    query = db.query(NHTSAComplaint).filter_by(company_id=entity_id)
    if model_year:
        query = query.filter(NHTSAComplaint.model_year == model_year)
    total = query.count()
    complaints = query.order_by(desc(NHTSAComplaint.date_of_complaint)).offset(offset).limit(limit).all()

    total_injuries = db.query(func.sum(NHTSAComplaint.injuries)).filter_by(company_id=entity_id).scalar() or 0
    total_deaths = db.query(func.sum(NHTSAComplaint.deaths)).filter_by(company_id=entity_id).scalar() or 0
    crash_count = db.query(NHTSAComplaint).filter_by(company_id=entity_id, crash=True).count()
    fire_count = db.query(NHTSAComplaint).filter_by(company_id=entity_id, fire=True).count()

    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "total_injuries": total_injuries,
        "total_deaths": total_deaths,
        "crash_count": crash_count,
        "fire_count": fire_count,
        "complaints": [
            {
                "id": c.id,
                "odi_number": c.odi_number,
                "make": c.make,
                "model": c.model,
                "model_year": c.model_year,
                "date_of_complaint": c.date_of_complaint,
                "crash": c.crash,
                "fire": c.fire,
                "injuries": c.injuries,
                "deaths": c.deaths,
                "component": c.component,
                "summary": c.summary,
            }
            for c in complaints
        ],
    }


@router.get("/companies/{entity_id}/safety-ratings")
def get_transportation_company_safety_ratings(
    entity_id: str,
    model_year: Optional[int] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    """NHTSA NCAP safety ratings for a transportation company."""
    co = db.query(TrackedTransportationCompany).filter_by(company_id=entity_id).first()
    if not co:
        raise HTTPException(status_code=404, detail="Transportation company not found")

    query = db.query(NHTSASafetyRating).filter_by(company_id=entity_id)
    if model_year:
        query = query.filter(NHTSASafetyRating.model_year == model_year)
    total = query.count()
    ratings = (
        query.order_by(desc(NHTSASafetyRating.model_year), NHTSASafetyRating.model)
        .offset(offset)
        .limit(limit)
        .all()
    )

    avg_overall = db.query(func.avg(NHTSASafetyRating.overall_rating)).filter(
        NHTSASafetyRating.company_id == entity_id,
        NHTSASafetyRating.overall_rating.isnot(None),
    ).scalar()

    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "avg_overall_rating": round(float(avg_overall), 1) if avg_overall else None,
        "ratings": [
            {
                "id": r.id,
                "vehicle_id": r.vehicle_id,
                "make": r.make,
                "model": r.model,
                "model_year": r.model_year,
                "overall_rating": r.overall_rating,
                "frontal_crash_rating": r.frontal_crash_rating,
                "side_crash_rating": r.side_crash_rating,
                "rollover_rating": r.rollover_rating,
            }
            for r in ratings
        ],
    }


@router.get("/companies/{entity_id}/fuel-economy")
def get_transportation_company_fuel_economy(
    entity_id: str,
    year: Optional[int] = Query(None),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
    db: Session = Depends(get_db),
):
    """EPA/DOE fuel economy data for a transportation company."""
    co = db.query(TrackedTransportationCompany).filter_by(company_id=entity_id).first()
    if not co:
        raise HTTPException(status_code=404, detail="Transportation company not found")

    query = db.query(FuelEconomyVehicle).filter_by(company_id=entity_id)
    if year:
        query = query.filter(FuelEconomyVehicle.year == year)
    total = query.count()
    vehicles = (
        query.order_by(desc(FuelEconomyVehicle.year), FuelEconomyVehicle.model)
        .offset(offset)
        .limit(limit)
        .all()
    )

    avg_mpg = db.query(func.avg(FuelEconomyVehicle.mpg_combined)).filter_by(company_id=entity_id).scalar()
    avg_co2 = db.query(func.avg(FuelEconomyVehicle.co2_tailpipe)).filter_by(company_id=entity_id).scalar()

    return {
        "total": total,
        "limit": limit,
        "offset": offset,
        "avg_mpg_combined": round(float(avg_mpg), 1) if avg_mpg else None,
        "avg_co2_tailpipe": round(float(avg_co2), 1) if avg_co2 else None,
        "vehicles": [
            {
                "id": v.id,
                "vehicle_id": v.vehicle_id,
                "year": v.year,
                "make": v.make,
                "model": v.model,
                "mpg_city": v.mpg_city,
                "mpg_highway": v.mpg_highway,
                "mpg_combined": v.mpg_combined,
                "co2_tailpipe": v.co2_tailpipe,
                "fuel_type": v.fuel_type,
                "vehicle_class": v.vehicle_class,
                "ghg_score": v.ghg_score,
                "smog_rating": v.smog_rating,
            }
            for v in vehicles
        ],
    }
