"""
Pydantic response models for sector factory endpoints.

These models are used as response_model on the 14 generic endpoints
generated by create_sector_router(). They document the exact response
shape in OpenAPI/Swagger and provide runtime validation.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


# ── Dashboard ───────────────────────────────────────────────────────────────


class SectorDashboardStats(BaseModel):
    """Generic sector dashboard stats. Extra keys allowed per sector."""
    total_lobbying: int = 0
    total_lobbying_spend: float = 0
    total_contracts: int = 0
    total_contract_value: float = 0
    total_enforcement: int = 0
    total_penalties: float = 0
    by_sector: Dict[str, int] = {}

    class Config:
        extra = "allow"


class ActivityMeta(BaseModel):
    class Config:
        extra = "allow"


class RecentActivityItem(BaseModel):
    type: str
    title: Optional[str] = None
    description: Optional[str] = None
    date: Optional[str] = None
    company_name: Optional[str] = None
    url: Optional[str] = None
    meta: Optional[Dict[str, Any]] = None

    class Config:
        extra = "allow"


class RecentActivityResponse(BaseModel):
    items: List[RecentActivityItem]


# ── Entity List ─────────────────────────────────────────────────────────────


class EntityListItem(BaseModel):
    display_name: Optional[str] = None
    ticker: Optional[str] = None
    sector_type: Optional[str] = None
    headquarters: Optional[str] = None
    logo_url: Optional[str] = None

    class Config:
        extra = "allow"


class EntityListResponse(BaseModel):
    total: int
    limit: int
    offset: int

    class Config:
        extra = "allow"


# ── Entity Detail ───────────────────────────────────────────────────────────


class StockSnapshot(BaseModel):
    ticker: Optional[str] = None
    snapshot_date: Optional[str] = None
    market_cap: Optional[float] = None
    pe_ratio: Optional[float] = None
    profit_margin: Optional[float] = None
    revenue: Optional[float] = None
    price: Optional[float] = None
    fifty_two_week_high: Optional[float] = None
    fifty_two_week_low: Optional[float] = None
    dividend_yield: Optional[float] = None

    class Config:
        extra = "allow"


class EntityDetailResponse(BaseModel):
    display_name: Optional[str] = None
    ticker: Optional[str] = None
    sector_type: Optional[str] = None
    headquarters: Optional[str] = None
    logo_url: Optional[str] = None
    sec_cik: Optional[str] = None
    ai_profile_summary: Optional[str] = None
    sanctions_status: Optional[str] = None
    filing_count: Optional[int] = None
    lobbying_count: int = 0
    contract_count: int = 0
    total_contract_value: float = 0
    enforcement_count: int = 0
    total_penalties: float = 0
    latest_stock: Optional[StockSnapshot] = None

    class Config:
        extra = "allow"


# ── Filings ─────────────────────────────────────────────────────────────────


class FilingItem(BaseModel):
    id: int
    accession_number: Optional[str] = None
    form_type: Optional[str] = None
    filing_date: Optional[str] = None
    primary_doc_url: Optional[str] = None
    filing_url: Optional[str] = None
    description: Optional[str] = None


class FilingsResponse(BaseModel):
    total: int
    limit: int
    offset: int
    filings: List[FilingItem]


# ── Contracts ───────────────────────────────────────────────────────────────


class ContractItem(BaseModel):
    id: int
    award_id: Optional[str] = None
    award_amount: Optional[float] = None
    awarding_agency: Optional[str] = None
    description: Optional[str] = None
    start_date: Optional[str] = None
    end_date: Optional[str] = None
    contract_type: Optional[str] = None
    ai_summary: Optional[str] = None


class ContractsResponse(BaseModel):
    total: int
    limit: int
    offset: int
    contracts: List[ContractItem]


class ContractSummaryResponse(BaseModel):
    total_contracts: int
    total_amount: float
    by_agency: Dict[str, int]


# ── Lobbying ────────────────────────────────────────────────────────────────


class LobbyingItem(BaseModel):
    id: int
    filing_uuid: Optional[str] = None
    filing_year: Optional[int] = None
    filing_period: Optional[str] = None
    income: Optional[float] = None
    expenses: Optional[float] = None
    registrant_name: Optional[str] = None
    client_name: Optional[str] = None
    lobbying_issues: Optional[str] = None
    government_entities: Optional[str] = None
    ai_summary: Optional[str] = None


class LobbyingResponse(BaseModel):
    total: int
    limit: int
    offset: int
    filings: List[LobbyingItem]


class LobbyingYearBreakdown(BaseModel):
    income: float = 0
    filings: int = 0


class LobbyingFirmBreakdown(BaseModel):
    income: float = 0
    filings: int = 0


class LobbySummaryResponse(BaseModel):
    total_filings: int
    total_income: float
    by_year: Dict[str, LobbyingYearBreakdown]
    top_firms: Dict[str, LobbyingFirmBreakdown]


# ── Enforcement ─────────────────────────────────────────────────────────────


class EnforcementItem(BaseModel):
    id: int
    case_title: Optional[str] = None
    case_date: Optional[str] = None
    case_url: Optional[str] = None
    enforcement_type: Optional[str] = None
    penalty_amount: Optional[float] = None
    description: Optional[str] = None
    source: Optional[str] = None
    ai_summary: Optional[str] = None


class EnforcementResponse(BaseModel):
    total: int
    total_penalties: float
    limit: int
    offset: int
    actions: List[EnforcementItem]


# ── Stock ───────────────────────────────────────────────────────────────────


class StockResponse(BaseModel):
    latest_stock: Optional[StockSnapshot] = None


# ── Donations ───────────────────────────────────────────────────────────────


class DonationItem(BaseModel):
    id: int
    committee_name: Optional[str] = None
    committee_id: Optional[str] = None
    candidate_name: Optional[str] = None
    candidate_id: Optional[str] = None
    person_id: Optional[str] = None
    amount: Optional[float] = None
    cycle: Optional[str] = None
    donation_date: Optional[str] = None
    source_url: Optional[str] = None


class DonationsResponse(BaseModel):
    total: int
    total_amount: float
    limit: int
    offset: int
    donations: List[DonationItem]


# ── Compare ─────────────────────────────────────────────────────────────────


class CompareEntityItem(BaseModel):
    display_name: Optional[str] = None
    ticker: Optional[str] = None
    sector_type: Optional[str] = None
    contract_count: int = 0
    total_contract_value: float = 0
    lobbying_total: float = 0
    enforcement_count: int = 0
    total_penalties: float = 0
    market_cap: Optional[float] = None
    pe_ratio: Optional[float] = None
    profit_margin: Optional[float] = None

    class Config:
        extra = "allow"


class CompareResponse(BaseModel):
    class Config:
        extra = "allow"


# ── Trends ──────────────────────────────────────────────────────────────────


class TrendSeries(BaseModel):
    lobbying: List[int]
    contracts: List[int]
    enforcement: List[int]


class TrendsResponse(BaseModel):
    years: List[int]
    series: TrendSeries
