"""
Twitter bot models — tweet logging, deduplication, draft replies,
and engagement analytics tracking.
"""

from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Float, Integer, String, Text
from sqlalchemy.sql import func

from models.database import Base


class TweetLog(Base):
    """Every tweet posted by the bot, for deduplication and analytics."""
    __tablename__ = "tweet_log"
    id = Column(Integer, primary_key=True)
    tweet_id = Column(String(50), index=True)
    category = Column(String(50), index=True)
    content_hash = Column(String(64), unique=True)
    text = Column(Text)
    posted_at = Column(DateTime, server_default=func.now())
    # Engagement metrics (populated by analytics collector job)
    impressions = Column(Integer, nullable=True)
    likes = Column(Integer, nullable=True)
    retweets = Column(Integer, nullable=True)
    replies = Column(Integer, nullable=True)
    quotes = Column(Integer, nullable=True)
    bookmarks = Column(Integer, nullable=True)
    # Engagement score: weighted composite for A/B comparison
    engagement_score = Column(Float, nullable=True)
    metrics_updated_at = Column(DateTime, nullable=True)


class DraftReply(Base):
    """Staged quote-tweet drafts generated by twitter_monitor.py.

    The monitor scans watchdog accounts, matches entities against
    the WTP database, and stores draft quote-tweets here. Drafts
    require human approval before posting (Gate 5 extension).

    Statuses: pending | approved | posted | rejected | skipped
    """
    __tablename__ = "draft_replies"
    id = Column(Integer, primary_key=True, index=True)
    target_tweet_id = Column(String, nullable=False, index=True)
    target_username = Column(String, nullable=False)
    target_text = Column(String, nullable=True)
    suggested_text = Column(String, nullable=False)
    matched_entity = Column(String, nullable=True)
    matched_data = Column(Text, nullable=True)  # JSON of lobbying/contract/trade data
    status = Column(String, server_default="pending")  # pending, approved, posted, rejected, skipped
    score = Column(Float, nullable=True)  # Data richness score for prioritization
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
    posted_at = Column(DateTime(timezone=True), nullable=True)


class TweetPerformance(Base):
    """Aggregated performance metrics by category and template.

    Updated daily by the analytics collector. Used for A/B testing
    and content strategy optimization.
    """
    __tablename__ = "tweet_performance"
    id = Column(Integer, primary_key=True)
    category = Column(String(50), nullable=False, index=True)
    # Time period for this aggregate
    period_start = Column(DateTime, nullable=False)
    period_end = Column(DateTime, nullable=False)
    # Metrics
    tweet_count = Column(Integer, default=0)
    total_impressions = Column(Integer, default=0)
    total_likes = Column(Integer, default=0)
    total_retweets = Column(Integer, default=0)
    total_replies = Column(Integer, default=0)
    avg_engagement_rate = Column(Float, default=0.0)
    # Best performing tweet in this period
    best_tweet_id = Column(String(50), nullable=True)
    best_engagement_score = Column(Float, nullable=True)
    # Metadata
    computed_at = Column(DateTime, server_default=func.now())
