"""
Twitter bot models — tweet logging, deduplication, and draft replies.
"""

from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, Integer, String, Text
from sqlalchemy.sql import func

from models.database import Base


class TweetLog(Base):
    __tablename__ = "tweet_log"
    id = Column(Integer, primary_key=True)
    tweet_id = Column(String(50))
    category = Column(String(50))
    content_hash = Column(String(64), unique=True)
    text = Column(Text)
    posted_at = Column(DateTime, server_default=func.now())


class DraftReply(Base):
    """
    Staged quote-tweet drafts generated by twitter_monitor.py.

    The monitor scans watchdog accounts, matches entities against
    the WTP database, and stores draft quote-tweets here.  Only one
    auto-quote is posted per day; the rest stay as 'pending' drafts
    for manual review or future posting.

    Statuses: pending | posted | skipped
    """
    __tablename__ = "draft_replies"
    id = Column(Integer, primary_key=True, index=True)
    target_tweet_id = Column(String, nullable=False)
    target_username = Column(String, nullable=False)
    target_text = Column(String, nullable=True)
    suggested_text = Column(String, nullable=False)
    matched_entity = Column(String, nullable=True)      # which WTP entity matched
    matched_data = Column(Text, nullable=True)           # JSON of matched lobbying/contract/trade data
    status = Column(String, server_default="pending")    # pending, posted, skipped
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    posted_at = Column(DateTime(timezone=True), nullable=True)
